title: Little Game

basic:
  fps: 8000
  num_items: 
    total: 5
    init_meat: 2
    init_bomb: 2
  level:
    threshold:
      - 30
      - 50
      - 100
      - 180
      - 220
    speed_scale: 1.25
    point_scale: 1.5
  full_score: 50
  typing:
    message: Congrats!! See you next time!
    speed: 0.2
    

screen:
  width: 800
  height: 400
  background_color:
    - 200   # r
    - 200   # g
    - 200   # b

scoreboard:
  text_color:
    - 30
    - 30
    - 30
  background_color:
    - 200   # r
    - 200   # g
    - 200   # b
  
button:
  start: 
    img: start.png
    scale: 0.8
  restart:
    img: restart.png
    scale: 0.2
  exit:
    img: exit.png
    scale: 0.8
  

dog:
  width: 80
  height: 80
  img:
    - dog1.png
    - dog2.png
    - hurt_dog1.png
    - hurt_dog2.png
  speed: 0.1
  img_refresh_rate: 500
  animation:
    rotate_speed: 0.18
    num_rotate: 1.5
    num_moving_step: 8000
    num_jumping: 3
    gravity:
      - 0
      - 0.0001


item:
  speed_variation: 1.1
  delay_variation: 1000

meat:
  width: 40
  height: 40
  img:
    - meat.png
  speed: 0.05
  point: 10

bomb:
  width: 40
  height: 40
  img:
    - bomb.png
  speed: 0.05
  point: -10

cake:
  width: 100
  height: 100
  scale: 0.8
  img:
    - cake.png
  speed: 0.02
  point: 15